- name: configure mysqul-server
  hosts: mysql
  become: yes 
  vars:
   mysql_root_password:  ExpenseApp@1
  tasks:  
  - name: Install mysqul libraries
    ansible.builtin.pip:
     name: "{{ item }}"
     exeutable: /usr/bin/python3
    loop:
    - cryptography
    - PyMySQL
  - name: install mysqul-server
    ansible.builtin.package:
     name: mysqul-server
     state: installed
  - name: start and enable mysqul-server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes
  - name: connect to mysqul-server
    community.mysql.mysql_info:
     login_user: root
     login_password: "{{ mysql_root_password }}"
     login_host: mysql.devops2024.fun
     register: mysql_info
     ignore_erroe: true
  - name: print the output
    ansible.builtin.debug:
     msg: "MYSQL_info:{{ mysql_info }}" 
  - name: setup root login_password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"  
    when: mysql_info.fail is true 

